Metrics/BlockLength:
  Exclude:
    - spec/**/*

# I don't want to write documentation for every class
Style/Documentation:
  Enabled: false

# I prefer raise to fail
Style/SignalException:
  EnforcedStyle: only_raise

# I prefer double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer hash rockets
Style/HashSyntax:
  EnforcedStyle: hash_rockets
